### PR TITLE
feat(Identity): Added netlify-identity-widget

### PR DESCRIPTION
**Pull request by vanhoofmaarten**
#### What does this PR contain?
Included a refactored version of the netlify-identity-widget from [gatsby-plugin-netlify-cms](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms).

This allows Netlify Identity to be used without configuration.
Eg. activations links, password reset links, ... 

#### Remarks:
The big number of changes on the package-lock.json is because I believe I am using the v6 version of NPM. [More info](https://github.com/npm/npm/issues/20891#issuecomment-395927417)

### CODE REVIEW

**Comment by tobymarsden** [comment]
@vanhoofmaarten Thank you! This looks great, and was something that was on my list but alas not quite at the top yet ;-)

Let me get it up and running and I'll merge it in the next couple of days.

**Comment by vanhoofmaarten** [comment]
My absolute pleasure.

**Comment by tobymarsden** [comment]
@vanhoofmaarten I had some trouble getting this running my side -- I needed to make a few tweaks here: 

[Branch](https://github.com/gethypervisual/gridsome-plugin-netlify-cms/tree/vanhoofmaarten-identity) | Commit https://github.com/gethypervisual/gridsome-plugin-netlify-cms/commit/42551e423714cdacd16e35ffce26e79a13c02e22

If you have a moment to check it, please do let me know if anything seems off as I don't use the Netlify Identity widget myself. I _think_ we're good to go, though!

**Comment by stursby** [comment]
+1 would love this feature! Nice work @vanhoofmaarten

**Comment by vanhoofmaarten** [comment]
@tobymarsden Thank you for your review. I'll try to check out your changes in the days to come.

**Comment by vanhoofmaarten** [comment]
@tobymarsden Looking good. All ready to go!

**Comment by tobymarsden** [comment]
@vanhoofmaarten Thanks so much -- published as v1.0.7

**Pull request merged**
